SELECT "sekolah"."jenjang", COUNT(1) AS "jumlah" 
FROM "datamart"."rombongan_belajar"
LEFT JOIN "datamart"."sekolah" AS "sekolah" ON "datamart"."rombongan_belajar"."sekolah_id"="sekolah"."sekolah_id"
GROUP BY "sekolah"."jenjang"
ORDER BY "sekolah"."jenjang"